server {
  # Nginx escuchará en el puerto 80 dentro del contenedor
  listen 80;

  # El directorio raíz donde se encuentran los archivos de nuestra app
  root /usr/share/nginx/html;

  # El archivo de entrada por defecto
  index index.html;

  # Configuración para el enrutamiento de la SPA (Single Page Application)
  location / {
    # Intenta servir el archivo solicitado directamente ($uri).
    # Si no lo encuentra, intenta servirlo como un directorio ($uri/).
    # Si todo lo anterior falla, devuelve el control a /index.html para que React Router funcione.
    try_files $uri $uri/ /index.html;
  }
}