spring.application.name=innovate-wear-backend

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/innovatewear_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Configuración del servidor
server.port=8080

# Configuración de logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
